apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: 1.24.0
    helm:
      values: |
        {{- .Files.Get "values/istio_cni_values.yaml" | nindent 8 }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: istio-system
  syncPolicy: 
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
