apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        {{- .Files.Get "values/minio_values.yaml" | nindent 8 }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: minio
  syncPolicy: 
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
