apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/heathj/k3s-vagrant.git
    targetRevision: HEAD
    path: infra/charts/nextcloud_pvc
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nextcloud
  syncPolicy: 
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
