apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics
  namespace: {{ .Values.spec.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts 
    chart: kube-prometheus-stack
    targetRevision: 56.2.0
    helm:
      values: |
        {{- .Files.Get "values/metrics_values.yaml" | nindent 8 }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: metrics
  syncPolicy: 
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
