apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-plans
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/heathj/k3s-vagrant.git'
    targetRevision: HEAD
    path: infra/charts/system_upgrade_plans
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: system-upgrade
  syncPolicy: 
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}
