resources:
  requests:
    memory: 512Mi
replicas: 1
persistence:
  enabled: false
mode: standalone
rootUser: rootuser
rootPassword: rootpass123
nodeSelector:
  jacobheath.xyz/usb-external-storage: "true"
