resources:
  requests:
    memory: 512Mi
replicas: 1
persistence:
  enabled: false
mode: standalone
rootUser: rootuser
rootPassword: rootpass123
nodeSelector:
  jacobheath.xyz/usb-external-storage: "true"
extraVolumes:
  - name: treebeard
    hostPath:
      path: /mnt/treebeard
      type: DirectoryOrCreate
  - name: largedrive
    hostPath:
      path: /mnt/largedrive
      type: DirectoryOrCreate
extraVolumeMounts:
  - name: treebeard
    mountPath: /mnt/treebeard
  - name: largedrive
    mountPath: /mnt/largedrive
