nextcloud:
  host: files.jacobheath.xyz
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - files.jacobheath.xyz
      secretName: files-jacobheath-xyz-tls
postgresql:
  enabled: true
redis:
  enabled: true
  architecture: standalone
metrics:
  enabled: true
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi
cronjob:
  enabled: true
