domain: &domain files.jacobheath.xyz
nextcloud:
  host: *domain
  trustedDomains:
    - *domain
  # datadir: /mnt/largedrive/data
  extraVolumeMounts:
    - name: largedrive
      mountPath: /mnt/largedrive
      readOnly: true
  extraVolumes:
    - name: largedrive
      nfs:
        server: nfs-service.nfs.svc.cluster.local
        path: /largedrive
livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  timeoutSeconds: 5
  periodSeconds: 60
  failureThreshold: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 300
  timeoutSeconds: 5
  periodSeconds: 60
  failureThreshold: 5
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-to-https@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - *domain
      secretName: files-jacobheath-xyz-tls
internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: &nextcloud-db-secret nextcloud-db-secret
    usernameKey: &usernameKey db-username
    passwordKey: &passwordKey db-password
    hostKey: db-hostname-or-ip
    databaseKey: db-name
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        existingSecret: *nextcloud-db-secret
        secretKeys:
          adminPasswordKey: *passwordKey
          userPasswordKey: *passwordKey
redis:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: *nextcloud-db-secret
    existingSecretPasswordKey: redis-password
metrics:
  enabled: true
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi
cronjob:
  enabled: true
