nextcloud:
  host: files.jacobheath.xyz
  extraVolumeMounts:
    - name: largedrive
      mountPath: /var/www/html/data
      subPath: data
  extraVolumes:
    - name: largedrive
      nfs:
        server: nfs-service.nfs.svc.cluster.local
        path: /largedrive/data
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - files.jacobheath.xyz
      secretName: files-jacobheath-xyz-tls
  internalDatabase:
    enabled: false
postgresql:
  enabled: true
redis:
  enabled: true
  architecture: standalone
metrics:
  enabled: true
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi
cronjob:
  enabled: true
