ingress:
  enabled: true
  className: istio
  annotations:
    # sidecar.istio.io/inject: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
postgresql:
  enabled: true
redis:
  enabled: true
metrics:
  enabled: true
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
cronjob:
  enabled: true
