nextcloud:
  host: files.jacobheath.xyz
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - files.jacobheath.xyz
      secretName: files-jacobheath-xyz-tls
postgresql:
  enabled: true
redis:
  enabled: true
metrics:
  enabled: true
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
cronjob:
  enabled: true
