providers:
  kubernetesIngress:
    enabled: true
resources:
  limits:
    cpu: 2
    memory: 500Mi
  requests:
    cpu: 2
    memory: 500Mi
extraObjects:
  - apiVersion: traefik.containo.us/v1alpha1
    kind: Middleware
    metadata:
      name: redirect-to-https
      namespace: traefik
    spec:
      redirectScheme:
        scheme: https
        permanent: true
