# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: {{ .Values.namespace}}
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  serviceAccountName: {{ .Values.serviceAccountName }}
  upgrade:
    image: {{ .Values.upgrade.image }}
  channel: {{ .Values.channel }}
---

# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: {{ .Values.namespace}}
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: {{ .Values.prepare.image }}
  serviceAccountName: {{ .Values.serviceAccountName }}
  upgrade:
    image: {{ .Values.upgrade.image }}
  channel: {{ .Values.channel }}