image:
  registry: lscr.io/linuxserver
  repository: plex
  tag: "arm64v8-latest"
ingress:
  enabled: true
  ingressClassName: "traefik"
  url: "https://plex.jacobheath.xyz"
pms:
  # the volume size to provision for the PMS database
  configStorage: 2Gi
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 2
    memory: 1Gi
service:
  type: ClusterIP
  port: 32400
extraVolumeMounts:
  - name: treebeard
    mountPath: /mnt/
extraVolumes:
  - name: treebeard
    nfs:
      server: nfs-service.storage.svc.cluster.local
      path: /
