apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: storage
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeSelector:
        jacobheath.xyz/usb-external-storage: "true"
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:11-arm
          env:
            - name: SHARED_DIRECTORY
              value: UNUSED # mounting a configmap over this
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - name: treebeard
              mountPath: /treebeard
            - name: largedrive
              mountPath: /largedrive
            - name: exports-volume
              mountPath: /etc/exports
              subPath: exports
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: treebeard
          hostPath:
            path: /mnt/treebeard
            type: DirectoryOrCreate
        - name: largedrive
          hostPath:
            path: /mnt/largedrive
            type: DirectoryOrCreate
        - name: exports-volume
          configMap:
            name: exports
