kind: Pod
apiVersion: v1
metadata:
  name: nfs-direct2
  namespace: storage
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: data
          mountPath: /demo/data
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
  volumes:
    - name: data
      nfs:
        server: nfs-service.storage.svc.cluster.local
        path: /
