apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: large-drive-data-dir-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  volumeName: large-drive-data-dir-pv
  storageClassName: ""
  volumeMode: Filesystem